import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f0f3ff",
        "surface-container-highest": "#d9e3f9",
        "tertiary-fixed": "#dce3eb",
        "surface-container-high": "#dee8fe",
        "secondary": "#00677e",
        "surface-tint": "#49607e",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-container": "#0a2540",
        "inverse-on-surface": "#ebf1ff",
        "secondary-container": "#00d2fd",
        "on-primary-fixed": "#001c37",
        "background": "#f9f9ff",
        "outline": "#74777e",
        "on-secondary-fixed-variant": "#004e5f",
        "on-primary-container": "#768dad",
        "tertiary": "#091015",
        "surface-bright": "#f9f9ff",
        "primary": "#000f22",
        "on-primary": "#ffffff",
        "on-secondary-container": "#005669",
        "inverse-surface": "#273141",
        "surface-dim": "#d0daf0",
        "primary-fixed": "#d2e4ff",
        "surface-variant": "#d9e3f9",
        "surface-container": "#e7eeff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#121c2b",
        "on-surface": "#121c2b",
        "secondary-fixed": "#b4ebff",
        "on-surface-variant": "#43474d",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#314865",
        "secondary-fixed-dim": "#3cd7ff",
        "on-secondary-fixed": "#001f27",
        "on-tertiary-fixed": "#151c22",
        "on-tertiary-fixed-variant": "#40484e",
        "outline-variant": "#c4c6ce",
        "primary-fixed-dim": "#b0c8eb",
        "surface": "#f9f9ff",
        "inverse-primary": "#b0c8eb",
        "on-error": "#ffffff",
        "tertiary-container": "#1e252b",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-tertiary-container": "#858c93",
        "error": "#ba1a1a",
        
        // Custom user colors for legacy compatibility
        navy: '#001C37',
        brandRed: '#D32F2F',
        muted: '#43474d',
        border: '#e2e8f0',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-tablet': '32px',
        'margin-desktop': '64px',
        'stack-xl': '120px',
        'stack-lg': '80px',
        'stack-md': '48px',
        'gutter': '32px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.8))',
      },
    },
  },
  plugins: [],
};

export default config;
